# 配置服务端口
server:
  port: 8080

spring:
  servlet:
    multipart:

      enabled: false

      max-file-size: 1GB

      max-request-size: 10GB

  redis:
    host: 127.0.0.1
    port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    listener:
      simple:
        retry:
          enabled: true  #开启消费者失败重试
          max-attempts: 5 #最大重试次数
          initial-interval: 1000ms #初始失败等待时长为1秒
          multiplier: 1 #下次失败的等待时长倍数，下次等待时长=multipiler*last-interval
        acknowledge-mode: manual #开启手动ack机制 auto是自动 none是发送后直接ack(这个不会用上的)


minio:
  config:
    url: http://127.0.0.1:9005 #ip地址
    accessKey: root #  账号
    secretKey: 15204931926 #  密码
    secure: false #如果是true，则用的是https而不是http,默认值是true
    bucketName: "test"  # 桶的名字 相当于文件夹
